### ISSUE TITLE
Update all videos

### ISSUE THREAD

**Issue by ArcticSubmarine** [csquare-ai/docs.csquare.run#16]

**Comment by ArcticSubmarine** [comment]
Is it done? @mathieu-bour

**Comment by matbour** [comment]
No, there will be updates due to CS-628 and CS-651.

**Comment by ArcticSubmarine** [comment]
Let's split this one @mathieu-bour

**Comment by matbour** [comment]
I'm pretty sure that it is basically endless. Better using Cypress to generate them.
